title: Portfolio
description: A modern portfolio website built with Jekyll
author: Ben Huang
email: benhua476@berkeley.edu
role: Software Developer
baseurl: ""
url: "https://benhuang3.github.io"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
