title: "~*~ Ben Huang's Homepage ~*~"
description: "Welcome to my GeoCities homepage! Software Developer from Berkeley"
author: Ben Huang
email: benhua476@berkeley.edu
role: Software Developer
baseurl: ""
url: "https://benhuang3.github.io"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: false
